version: '3'
services:
  # Frontend (React)
  frontend:
    build:
      context: ./portal2 # Path to your frontend directory containing the Dockerfile
    container_name: web
    ports:
      - "3000:3000" # Expose the frontend on port 3000

  # Backend (Node.js and Express)
  backend:
    build:
      context: ./backend # Path to your backend directory containing the Dockerfile
    container_name: api
    ports:
      - "3001:3001" # Expose the backend on port 3001
    environment:
      - MONGO_URL=mongodb+srv://root:root@cluster0.5hksbic.mongodb.net/ # MongoDB connection URI
    depends_on:
      - mongo

  # MongoDB
  mongo:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    environment:
      - MONGO_INITDB_DATABASE=uruws # Replace with your desired database name
